// <auto-generated />
using System;
using MASProject.Server.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MASProject.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240617191545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("MASProject.Server.Models.LodgingModels.Lodging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Amenities")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BreakfastIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LodgingType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialWebsiteURL")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lodgings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            Description = "Description 1",
                            Email = "hotel@example.com",
                            LodgingType = 0,
                            Name = "Hotel 1",
                            PhoneNumber = "2321231123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            Description = "Description 2",
                            Email = "hotelnew@example.com",
                            LodgingType = 0,
                            Name = "Hotel 2",
                            PhoneNumber = "3232323222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            Description = "Description 3",
                            Email = "inn@example.com",
                            LodgingType = 0,
                            Name = "Inn 1",
                            PhoneNumber = "098776512"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address 4",
                            Description = "Description 4",
                            Email = "innnew@example.com",
                            LodgingType = 0,
                            Name = "Inn 2",
                            PhoneNumber = "3232323232"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.LodgingModels.LodgingBooking", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LodgingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasPrecision(2)
                        .HasColumnType("REAL");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TourId", "LodgingId");

                    b.HasIndex("LodgingId");

                    b.ToTable("LodgingBookings");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            LodgingId = 1,
                            CheckInDate = new DateOnly(2025, 1, 1),
                            CheckOutDate = new DateOnly(2025, 2, 2),
                            MaxCapacity = 1,
                            Price = 100f,
                            RoomType = "Single"
                        },
                        new
                        {
                            TourId = 1,
                            LodgingId = 2,
                            CheckInDate = new DateOnly(2025, 3, 1),
                            CheckOutDate = new DateOnly(2025, 4, 2),
                            MaxCapacity = 2,
                            Price = 200f,
                            RoomType = "Double"
                        },
                        new
                        {
                            TourId = 2,
                            LodgingId = 3,
                            CheckInDate = new DateOnly(2025, 4, 1),
                            CheckOutDate = new DateOnly(2025, 5, 2),
                            MaxCapacity = 1,
                            Price = 100f,
                            RoomType = "Single"
                        },
                        new
                        {
                            TourId = 2,
                            LodgingId = 4,
                            CheckInDate = new DateOnly(2025, 5, 1),
                            CheckOutDate = new DateOnly(2025, 6, 2),
                            MaxCapacity = 2,
                            Price = 200f,
                            RoomType = "Double"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.TourModels.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagesURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Popularity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Discover the lesser-traveled depths of Antelope Canyon on a walking tour through the lower portions of this colorful sandstone slot canyon.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/7f/67/da.jpg https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/90/31/4c/caption.jpg https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/8f/68/c5/caption.jpg https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/8f/68/ca/caption.jpg",
                            Title = "Lower Antelope Canyon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover the highlights of several cities in the Northeast on this 4-day sightseeing tour by bus or minivan from Boston.",
                            ImagesURL = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/46/b6/9c/20161010-133807-largejpg.jpg https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/7d/1f/18/photo3jpg.jpg https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/d4/be/31/view-from-one-of-the_rotated_90.jpg",
                            Title = "Niagara Falls"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ideal for travelers short on time, this tour covers the Grand Canyon’s South Rim in one day of sightseeing from Las Vegas.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/33.jpg https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/3e.jpg",
                            Title = "Grand Canyon"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Journey to Horseshoe Bend on a guided tour that includes all your entrance fees, round-trip transport from Flagstaff, and a picnic lunch.",
                            ImagesURL = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/56/c1/06/horseshoe-bend-az.jpg",
                            Title = "Horseshoe Bend"
                        },
                        new
                        {
                            Id = 5,
                            Description = "This man-made reservoir, located in northern Arizona and southern Utah, is a great spot for travelers seeking nature and outdoor adventure.",
                            ImagesURL = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/91/5b/02/morning-at-the-lake-powell.jpg",
                            Title = "Lake Powell"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Avoid crowds and maximize your wildlife-viewing experience on this private Yellowstone tour led by a naturalist guide.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/8e/af/dd.jpg",
                            Title = "Yellowstone Tour"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Immerse yourself in the majestic beauty of Yosemite National Park on this 2-day overnight adventure from San Francisco. Great way to spend holidays.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0b/2b/8a/7e.jpg",
                            Title = "Yosemite Valley"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Explore the Incredible Narrows portion of Zion National Park without the risk of getting lost on this private full-day tour. A fun day out for travelers.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/2c/ff/9e.jpg",
                            Title = "The Narrows"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Discover the stunning landscape of Bryce Canyon National Park on a full-day tour from Las Vegas that features a scenic round-trip journey by air.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/33.jpg",
                            Title = "Bryce Canyon"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Explore Monument Valley Navajo Tribal Park on a full-day tour that features a visit to the Navajo Nation’s largest trading post.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/33.jpg",
                            Title = "Monument Valley"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Discover the natural beauty of Arches National Park on this tour from Moab. A great way to spend a day out.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/33.jpg",
                            Title = "Arches National Park"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Discover the natural beauty of Canyonlands National Park on this tour from Moab. A great way to spend a day out.",
                            ImagesURL = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0a/9a/19/33.jpg",
                            Title = "Canyonlands National Park"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.TourModels.TourPurchase", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TourStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("TourPurchases");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            CustomerId = 1,
                            PaymentDate = new DateOnly(2024, 10, 1),
                            PaymentMethod = 2,
                            TourStatus = 1
                        },
                        new
                        {
                            TourId = 2,
                            CustomerId = 2,
                            PaymentDate = new DateOnly(2024, 9, 2),
                            PaymentMethod = 1,
                            TourStatus = 1
                        },
                        new
                        {
                            TourId = 3,
                            CustomerId = 3,
                            PaymentDate = new DateOnly(2024, 8, 3),
                            PaymentMethod = 0,
                            TourStatus = 1
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AirConditioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CargoCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransportType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Transports");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Transport");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.TransportBooking", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasPrecision(2)
                        .HasColumnType("REAL");

                    b.HasKey("TourId", "TransportId");

                    b.HasIndex("TransportId");

                    b.ToTable("TransportBookings");

                    b.HasData(
                        new
                        {
                            TourId = 1,
                            TransportId = 1,
                            ArrivalTime = new DateTime(2024, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2024, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Lagos",
                            Origin = "Abuja",
                            Price = 5000f
                        },
                        new
                        {
                            TourId = 2,
                            TransportId = 2,
                            ArrivalTime = new DateTime(2024, 12, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2024, 12, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            Origin = "Lagos",
                            Price = 5000f
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.UserModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.Plane", b =>
                {
                    b.HasBaseType("MASProject.Server.Models.TransportModels.Transport");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Plane");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 660,
                            CargoCapacity = 875,
                            Company = "Boeing",
                            Description = "The Boeing 747 is a large, long–range wide-body airliner designed and manufactured by Boeing Commercial Airplanes in the United States. It is among the world's most recognizable aircraft and was the first wide-body produced. Manufactured from 1968 to 2021, the 747 held the passenger capacity record for 37 years.",
                            MaxSpeed = 614,
                            TransportType = 0,
                            Amenities = "Wi-Fi#In-flight entertainment#Power outlets",
                            Model = "Boeing 747"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 853,
                            CargoCapacity = 1500,
                            Company = "Airbus",
                            Description = "The Airbus A380 is a wide-body aircraft manufactured by Airbus. It is the world's largest passenger airliner. Airbus studies started in 1988 and the project was announced in 1990 to challenge the dominance of the Boeing 747 in the long haul market.",
                            MaxSpeed = 587,
                            TransportType = 0,
                            Amenities = "Wi-Fi#In-flight entertainment#Power outlets",
                            Model = "Airbus A380"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 550,
                            CargoCapacity = 1000,
                            Company = "Boeing",
                            Description = "The Boeing 777 is a wide-body airliner developed and manufactured by Boeing Commercial Airplanes. It is the world's largest twinjet. The 777 was designed to bridge the gap between Boeing's other wide-body airliners and the 747.",
                            MaxSpeed = 590,
                            TransportType = 0,
                            Amenities = "Wi-Fi#In-flight entertainment#Power outlets",
                            Model = "Boeing 777"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 440,
                            CargoCapacity = 1000,
                            Company = "Airbus",
                            Description = "The Airbus A350 is a long-range, wide-body jet airliner developed by Airbus. The A350 is the first Airbus aircraft with both fuselage and wing structures made primarily of carbon-fibre-reinforced polymer. Its variants seat 280 to 366 passengers in typical three-class seating layouts.",
                            MaxSpeed = 567,
                            TransportType = 0,
                            Amenities = "Wi-Fi#In-flight entertainment#Power outlets",
                            Model = "Airbus A350"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 330,
                            CargoCapacity = 1000,
                            Company = "Boeing",
                            Description = "The Boeing 787 Dreamliner is an American wide-body jet airliner manufactured by Boeing Commercial Airplanes. Launched in April 2004, the 787 was designed to be more fuel-efficient than the Boeing 767, which it was intended to replace. The 787 Dreamliner's distinguishing features include mostly electrical flight systems, raked wingtips, and noise-reducing chevrons on its engine nacelles.",
                            MaxSpeed = 593,
                            TransportType = 0,
                            Amenities = "Wi-Fi#In-flight entertainment#Power outlets",
                            Model = "Boeing 787"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.Train", b =>
                {
                    b.HasBaseType("MASProject.Server.Models.TransportModels.Transport");

                    b.Property<int>("Classes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Train");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            AirConditioning = true,
                            Capacity = 100,
                            Company = "Train Company",
                            Description = "This is a train",
                            TransportType = 1,
                            Classes = 3,
                            TrainNumber = "123"
                        },
                        new
                        {
                            Id = 7,
                            AirConditioning = true,
                            Capacity = 100,
                            Company = "Train Company 2",
                            Description = "This is a train 2",
                            TransportType = 1,
                            Classes = 4,
                            TrainNumber = "456"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.UserModels.Admin", b =>
                {
                    b.HasBaseType("MASProject.Server.Models.UserModels.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("MASProject.Server.Models.UserModels.Customer", b =>
                {
                    b.HasBaseType("MASProject.Server.Models.UserModels.User");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1, 1, 1),
                            Name = "John",
                            Password = "password",
                            Surname = "Doe",
                            Username = "johndoe",
                            Email = "john@doe.com",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1, 1, 1),
                            Name = "Jane",
                            Password = "password",
                            Surname = "Doe",
                            Username = "janedoe",
                            Email = "jane@doe.com",
                            PhoneNumber = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1, 1, 1),
                            Name = "Alice",
                            Password = "password",
                            Surname = "Smith",
                            Username = "alicesmith",
                            Email = "alice@smith.com",
                            PhoneNumber = "123123123"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1, 1, 1),
                            Name = "Bob",
                            Password = "password",
                            Surname = "Smith",
                            Username = "bobsmith",
                            Email = "bob@smith.com",
                            PhoneNumber = "456456456"
                        });
                });

            modelBuilder.Entity("MASProject.Server.Models.LodgingModels.LodgingBooking", b =>
                {
                    b.HasOne("MASProject.Server.Models.LodgingModels.Lodging", "Lodging")
                        .WithMany("LodgingBookings")
                        .HasForeignKey("LodgingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASProject.Server.Models.TourModels.Tour", "Tour")
                        .WithMany("LodgingBookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lodging");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("MASProject.Server.Models.TourModels.TourPurchase", b =>
                {
                    b.HasOne("MASProject.Server.Models.UserModels.Customer", "Customer")
                        .WithMany("TourPurchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASProject.Server.Models.TourModels.Tour", "Tour")
                        .WithMany("TourPurchases")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.TransportBooking", b =>
                {
                    b.HasOne("MASProject.Server.Models.TourModels.Tour", "Tour")
                        .WithMany("TransportBookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MASProject.Server.Models.TransportModels.Transport", "Transport")
                        .WithMany("TransportBookings")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("MASProject.Server.Models.LodgingModels.Lodging", b =>
                {
                    b.Navigation("LodgingBookings");
                });

            modelBuilder.Entity("MASProject.Server.Models.TourModels.Tour", b =>
                {
                    b.Navigation("LodgingBookings");

                    b.Navigation("TourPurchases");

                    b.Navigation("TransportBookings");
                });

            modelBuilder.Entity("MASProject.Server.Models.TransportModels.Transport", b =>
                {
                    b.Navigation("TransportBookings");
                });

            modelBuilder.Entity("MASProject.Server.Models.UserModels.Customer", b =>
                {
                    b.Navigation("TourPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
